version: '3'
services:
  # #postgresql用コンテナ
  postgres:
    # Docker Image は postgres:12-alpine を使います。postgres:12-alpine は postgres:12 と比較して、イメージサイズが小さくなっています。
    image: postgres:12-alpine
    # コンテナの名前を指定します。
    container_name: postgres
    # 環境変数を設定します。
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    # データの永続化
    volumes:
      # postgresディレクトリを/var/lib/postgresql/dataにマウントする
      - postgres:/var/lib/postgresql/data
    # ポートの指定（HOST:CONTAINER）
    ports:
      - 5432:5432
  # #phpMyAdmin用コンテナ
  # phpmyadmin:
  #   container_name: phpMyAdmin
  #   depends_on:
  #     - mysql
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: mysql
  #   restart: always
  #   ports:
  #     - "80:80"

  #php用コンテナ
  php:
    container_name: php-apache
    build: ./php
    volumes:
      - ./html:/var/www/html
      - ./output:/var/www/html/output
    ports:
      - 8080:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   - mysql
# データの永続化
volumes:
  postgres:
